// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ARDUINO_H
#define ARDUINO_H
#include "frc/commands/Subsystem.h"
#include "frc/WPILib.h"
#include <frc/I2C.h>

#define ARDUINO_LED_COMMAND 0xA
#define ARDUINO_DISTANCE_COMMAND 0xF

typedef enum
{
	E_REQUEST_LED = 0,
	E_REQUEST_DISTANCE_SENSOR = 1,
	E_INVALID_TYPE
} E_ARDUINO_REQUEST_TYPE;

class Arduino: public frc::Subsystem {
private:
	frc::I2C *i2c;
    char _commandChar;
    uint32_t _responseInt;
    uint32_t _distSensorValue;
    unsigned char arduinoData[10];

    void SendLEDUpdate(int subsystem);
    uint8_t GetCommandCharFromRequest(E_ARDUINO_REQUEST_TYPE t);

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	Arduino();
	void InitDefaultCommand() override;
	void Periodic() override;
	uint32_t GetDistanceSensor();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS


};

#endif
