// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Commands/DriveByJoystick.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

DriveByJoystick::DriveByJoystick(): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void DriveByJoystick::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void DriveByJoystick::Execute() {

    double motorL = 0.0;
    double motorR = 0.0;
    
    
    motorL = Robot::oi->getDeadZoneCorrected(Robot::oi->getJoyL()->GetRawAxis(1));
	motorR = Robot::oi->getDeadZoneCorrected(Robot::oi->getJoyR()->GetRawAxis(1));
    //motorL = Robot::oi->getJoyL()->GetRawAxis(1);
    //motorR = Robot::oi->getJoyR()->GetRawAxis(1);
    
	Robot::driveTrain->TankDrive(motorL, motorR);

}

// Make this return true when this Command no longer needs to run execute()
bool DriveByJoystick::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void DriveByJoystick::End() {
    Robot::driveTrain->TankDrive(0.0, 0.0);

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DriveByJoystick::Interrupted() {

}
